require "rails/generators/named_base"

module OmniAgent
  module Generators
    class McpServerGenerator < Rails::Generators::NamedBase
      desc "Creates an OmniAgent MCP server in app/mcp_servers and mounts it in config/routes.rb"

      class_option :with_tools,
                   type: :array,
                   default: nil,
                   lazy_default: [],
                   banner: "[Tool1 Tool2 ...]",
                   desc: "Scaffold server-local tools in app/mcp_servers/<name>_server/tools. Optionally pass tool names"
      class_option :tools,
                   type: :array,
                   default: [],
                   banner: "[ResearchAgent::Tools::GetWeather ...]",
                   desc: "Existing tool classes to expose"
      class_option :agents,
                   type: :array,
                   default: [],
                   banner: "[ResearchAgent ...]",
                   desc: "Agents whose tools are all exposed (tools_from)"
      class_option :path,
                   type: :string,
                   default: nil,
                   desc: "Mount path for the HTTP endpoint (default: /mcp/<name>)"

      def create_server_file
        create_file(File.join("app", "mcp_servers", "#{server_file_name}.rb"), server_template)
      end

      def create_tools_if_requested
        return if options[:with_tools].nil?

        requested_tool_names.each do |tool_name|
          create_file(File.join("app", "mcp_servers", server_file_name, "tools", "#{tool_name.underscore}.rb"), tool_template(tool_name))
        end
      end

      def mount_route
        if mounts_all_servers?
          say_status :skip, "config/routes.rb already mounts every server with `mcp_servers`", :yellow
          return
        end

        route_line = "mcp_server #{server_slug.include?('/') ? server_slug.inspect : ":#{server_slug}"}"
        route_line += %(, path: "#{options[:path]}") if options[:path].present?
        route route_line
      end

      def show_next_steps
        say ""
        say "MCP server #{server_class_name} created."
        say ""
        say "Set a token, start the app and connect Claude Code over HTTP:"
        say "  #{token_env_var}=change-me bin/rails server"
        say "  claude mcp add --transport http #{server_identifier} http://localhost:3000#{mount_path} --header \"Authorization: Bearer change-me\""
        say ""
        say "Or run it locally over stdio (no HTTP auth; see stdio_principal):"
        say "  claude mcp add #{server_identifier} -- bundle exec omni_agent mcp #{server_class_name}"
      end

      private

      def server_class_name
        class_name.end_with?("Server") ? class_name : "#{class_name}Server"
      end

      def server_file_name
        server_class_name.underscore
      end

      def server_slug
        OmniAgent::MCP::Routing.slug_for(server_class_name)
      end

      def server_identifier
        server_slug.tr("/", "_")
      end

      def mount_path
        options[:path].presence || "#{OmniAgent::MCP::Routing::DEFAULT_PATH_PREFIX}/#{server_slug.dasherize}"
      end

      def mounts_all_servers?
        routes_file = File.join(destination_root, "config", "routes.rb")
        File.exist?(routes_file) && File.read(routes_file).match?(/^\s*mcp_servers\s*(\(\s*\)|except:.*)?\s*$/)
      end

      def token_env_var
        "#{server_identifier.upcase}_MCP_TOKENS"
      end

      def server_template
        <<~RUBY
          class #{server_class_name} < OmniAgent::MCP::Server
            instructions "Tools exposed by #{server_class_name}."

          #{tool_lines.map { |line| "  #{line}" }.join("\n")}

            # Comma-separated list of accepted bearer tokens.
            authenticate :bearer, tokens: -> { ENV.fetch("#{token_env_var}", "").split(",") }

            # Hide tools per principal:
            # authorize_tool { |tool_class, principal| true }

            # Extra values merged into each tool's `context`:
            # context { |principal, request| { current_user: principal } }
          end
        RUBY
      end

      def requested_tool_names
        names = Array(options[:with_tools]).map(&:strip).reject(&:empty?)
        names.empty? ? [ "ExampleTool" ] : names.map(&:camelize)
      end

      def tool_template(tool_name)
        <<~RUBY
          module #{server_class_name}::Tools
            class #{tool_name} < OmniAgent::Tool
              description "#{tool_name} generated by omni_agent:mcp_server"
              annotations read_only: true

              input do
                string :input_text, description: "Text input"
              end

              def execute(input_text:)
                "Echo: \#{input_text}"
              end
            end
          end
        RUBY
      end

      def tool_lines
        tools = Array(options[:tools]).map(&:strip).reject(&:empty?)
        agents = Array(options[:agents]).map(&:strip).reject(&:empty?)

        lines = []
        lines << "tools #{tools.join(', ')}" if tools.any?
        lines.concat(agents.map { |agent| "tools_from #{agent}" })
        lines.unshift("# Tools in app/mcp_servers/#{server_file_name}/tools/ are added automatically.")
        lines << "# tools SomeAgent::Tools::SomeTool" if tools.empty? && agents.empty?
        lines
      end
    end
  end
end
