require "rails/generators/named_base"
require "fileutils"

module OmniAgent
  module Generators
    class AgentGenerator < Rails::Generators::NamedBase
      class_option :with_tools,
                   type: :array,
                   default: nil,
                   banner: "[Tool1 Tool2 ...]",
                   desc: "Create tools folder and scaffold tools. Optionally pass tool names"
      class_option :model,
                   type: :string,
                   default: nil,
                   desc: "Override the model used in use_model for the generated agent"

      def create_agent_structure
        FileUtils.mkdir_p(agent_directory)

        create_file(agent_file_path, <<~RUBY)
          class #{class_name} < OmniAgent::Agent
            use_model #{generated_model_expression}
          end
        RUBY

        create_file(prompt_file_path, <<~ERB)
          You are #{class_name}, a helpful assistant with access to local tools.
        ERB
      end

      def create_tools_if_requested
        return unless with_tools_requested?

        FileUtils.mkdir_p(tools_directory)

        scaffold_names = requested_tool_names
        scaffold_names.each do |tool_name|
          create_file(tool_file_path(tool_name), tool_template(tool_name))
        end
      end

      private

      def agent_directory
        File.join(destination_root, "app", "agents", file_name)
      end

      def agent_file_path
        File.join(destination_root, "#{file_name}.rb")
      end

      def prompt_file_path
        File.join(agent_directory, "prompt.md.erb")
      end

      def tools_directory
        File.join(agent_directory, "tools")
      end

      def tool_file_path(tool_name)
        File.join(tools_directory, "#{tool_name.to_s.underscore}.rb")
      end

      def tool_template(tool_name)
        tool_class = tool_name.to_s.camelize

        <<~RUBY
          module #{class_name}::Tools
            class #{tool_class} < OmniAgent::Tool
              description "#{tool_class} generated by omni_agent:agent"
              tags :example
              metadata category: :demo

              input do
                string :input_text, description: "Text input"
              end

              def execute(input_text:)
                "Echo: \#{input_text}"
              end
            end
          end
        RUBY
      end

      def with_tools_requested?
        !options[:with_tools].nil?
      end

      def requested_tool_names
        names = Array(options[:with_tools]).map(&:to_s).map(&:strip).reject(&:empty?)
        names.empty? ? [ "ExampleTool" ] : names
      end

      def generated_model_expression
        model = options[:model].to_s.strip
        return "OmniAgent.configuration.default_model" if model.empty?

        model.inspect
      end
    end
  end
end
