require "fileutils"

namespace :omni_agent do
	desc "Set up OmniAgent directories in your Rails app"
	task install: :environment do
		agents_root = Rails.root.join("app", "agents")
		FileUtils.mkdir_p(agents_root)

		puts "Created #{agents_root}"
		puts "OmniAgent install complete."
		puts "Next: bundle exec rake \"omni_agent:create_agent[ResearchAgent]\""
	end

	desc "Create an agent scaffold. Usage: rake \"omni_agent:create_agent[ResearchAgent]\" [-- --with-tools]"
	task :create_agent, [:name] => :environment do |_task, args|
		agent_name = args[:name].to_s.strip

		if agent_name.empty?
			abort "Please provide an agent name. Example: bundle exec rake \"omni_agent:create_agent[ResearchAgent]\""
		end

		with_tools = ARGV.include?("--with-tools")

		agent_file_name = "#{agent_name.underscore}.rb"
		agent_dir_name = agent_name.underscore
		agent_dir = Rails.root.join("app", "agents", agent_dir_name)
		tools_dir = agent_dir.join("tools")
		prompt_file = agent_dir.join("prompt.md.erb")
		agent_rb = agent_dir.join(agent_file_name)

		FileUtils.mkdir_p(agent_dir)

		if File.exist?(agent_rb)
			abort "Agent file already exists: #{agent_rb}"
		end

		File.write(agent_rb, <<~RUBY)
			class #{agent_name} < OmniAgent::Agent
			end
		RUBY

		unless File.exist?(prompt_file)
			File.write(prompt_file, <<~PROMPT)
				You are #{agent_name}, a helpful assistant with access to local tools.
			PROMPT
		end

		if with_tools
			FileUtils.mkdir_p(tools_dir)

			example_tool = tools_dir.join("example_tool.rb")
			unless File.exist?(example_tool)
				File.write(example_tool, <<~RUBY)
					module #{agent_name}::Tools
						class ExampleTool < OmniAgent::Tool
							description "Example tool generated by omni_agent:create_agent"
							tags :example
							metadata category: :demo

							input do
								string :input_text, description: "Text to echo back"
							end

							def execute(input_text:)
								"Echo: \#{input_text}"
							end
						end
					end
				RUBY
			end
		end

		puts "Created #{agent_rb}"
		puts "Created #{prompt_file}" if File.exist?(prompt_file)
		puts "Created #{tools_dir}" if with_tools
		puts "Created #{tools_dir.join("example_tool.rb")}" if with_tools && File.exist?(tools_dir.join("example_tool.rb"))
	end
end
